flexmodel:
  datasource:
    db-kind: sqlite
    url: jdbc:sqlite:file:sqlite.db
    metacode:
      db-kind: sqlite
      url: jdbc:sqlite:file:sqlite.db

quarkus:
  swagger-ui:
    always-include: true
